name: Browserstack

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm ci
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit
        env:
          CI: true
          NODE_ENV: test

  browserstack:
    runs-on: ubuntu-latest
    needs: unit-tests

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: "BrowserStack Env Setup"
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: "Start BrowserStackLocal Tunnel"
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: "start"
          local-logging-level: "all-logs"
          local-identifier: "random"

      - uses: actions/checkout@v4

      - name: Prettier Action on PR
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: "--write {**/*,*}.{js,hbs,html,json,md,yml,css,scss} !.github/workflows/**/* !dist/**/*"
          commit_message: "Run prettier via GitHub Action"
          file_pattern: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm ci
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run BrowserStack tests
        run: node ./test/index.js
        env:
          CI: true
          NODE_ENV: test
          DEBUG: false
          LOCATION: ${{ secrets.LOCATION }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: "Stop BrowserStackLocal"
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: "stop"
